<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())) ?>" method="post">
	<input type="hidden" name="_csrf" value="<?=  FreshRSS_Auth::csrfToken() ?>" />
	<div class="form-group">
		<h4><?= _t('ext.flaresolverr.explanation') ?></h4>
		<label class="checkbox" for="flaresolver_url"><?= _t('ext.flaresolverr.instruction') ?></label>
		<div class="group-controls">
			<input type="text" id="flaresolver_url" name="flaresolver_url" value="<?= $this->getFlaresolverUrl() ?>">
		</div>

	</div>



	<div class="form-group">
		<label class="checkbox" for="flaresolver_url"><?= _t('ext.flaresolverr.maxTimeout') ?></label>
		<div class="group-controls">
			<input type="text" id="flaresolver_maxTimeout" name="flaresolver_maxTimeout" value="<?= $this->getMaxTimeout() ?>">
		</div>
	</div>


	<div class="form-group">
		<label class="checkbox" for="flaresolver_url"><?= _t('ext.flaresolverr.prepend') ?></label>
		<div class="group-controls">
			<b><?= $this->getPluginEndpoint() ?></b>
		</div>
	</div>


	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
		</div>
	</div>
</form>

<p>
	<?= _t('ext.flaresolverr.updates', '<a href="https://github.com/ravenscroftj/freshrss-flaresolverr-extension" alt="GitHub" target="_blank">GitHub</a>') ?>
</p>
