<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())) ?>" method="post">
	<input type="hidden" name="_csrf" value="<?=  FreshRSS_Auth::csrfToken() ?>" />
	<div class="form-group">

		<h4><?= _t('ext.flaresolverr.explanation') ?></h4>

		<p><?= _t('ext.flaresolverr.instruction') ?></p>

		<div class="group-controls">
			<label class="checkbox" for="flaresolver_url">
				<input type="text" id="flaresolver_url" name="flaresolver_url" value="<?= $this->getFlaresolverUrl() ?>">
			</label>
		</div>

                <p>Prepend your feed URL with: <b><?= $this->getPluginEndpoint() ?></b></p>

	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
		</div>
	</div>
</form>

<p>
	<?= _t('ext.greader_redate.updates') ?>
	<a href="https://github.com/javerous/freshrss-greader-redate" target="_blank">GitHub</a>.
</p>
